name: Deploy with OIDC

on:
  push:
    branches: [main]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: d6e6711c-4923-451c-b0c4-5b0068bbc298
          tenant-id: fdd066e1-ee37-49bc-b08f-d0e152119b04
          subscription-id: f89fc1d7-0449-4b52-bdd7-804f53711a6f

      - name: Azure CLI Script
        run: |
          az account show # Verifies authentication
          # Run your deployment commands here   
